### ISSUE TITLE
Add support for machines on the same IPv4 address

### ISSUE THREAD

**Issue by Sora3100** [btbd/mmultiplayer#1]
I tried to test this in my LAN via my desktop and laptop (both connected via cable) but the 2 devices couldn't see each other outside of the messages,

Both had it's firewall turned off and are running Windows 10 1709 x64
And yes, both the game and mod exe were running as admin on both machines

Also /help command would be appreciated along with error messages for unknown commands, and also some logs.

**Comment by btbd** [comment]
LAN is currently not supported.

**Comment by Sora3100** [comment]
So how does one connect over the internet?
Open port 2783 and be in the same room?

**Comment by btbd** [comment]
Yes. However, the method the program sends packets directly to other clients won't work properly with machines on the same network. This and more debug info should be added in the next release.

**Comment by Hiteke** [comment]
Add LAN support

**Comment by btbd** [comment]
Sorry for the inactivity, now fixed with 2.0.
