### ISSUE TITLE
3659 ISSUE

### ISSUE THREAD

**Issue by Athenashout** [btbd/mmultiplayer#16]
Hi there, 

The mod already worked in the past although today when launching it again an issue occurred :

"Check your network connection and make sure that port 3659 is open" 

I already tried following what the Read me outlet suggested but since there are no further explanations I can't seem to make it work. I tried what seems like a hundred different kinds of things but nothing works. When I finally figured how to open this very same port, the log simply does not open anymore.

Do you have any more information that could solve the problem?

Thanks in advance,

Athena

**Comment by btbd** [comment]
@Athenashout Try version 2.0, should fix all these issues.
