### ISSUE TITLE
Windows flags  MMultiplayer_Launcher.exe as a Trojan

### ISSUE THREAD

**Issue by pleatherbreakfast** [btbd/mmultiplayer#20]
Windows flags the exe as a Trojan almost immidiately. Just wanted to ask what gives and how to get around it? Excluding doesn't seem to work.

**Comment by btbd** [comment]
@pleatherbreakfast Windows flags it because the file is not signed, connects to the internet, and injects a DLL into another process. You should be able to add an exclusion for the file in Windows Defender. If you cannot do that then your other option is just disable Windows Defender.
