### ISSUE TITLE
Menu does not open (Client.dll issue).

### ISSUE THREAD

**Issue by Veratosian** [btbd/mmultiplayer#21]
After opening the launcher executable file (with administrator rights) and launching the game pressing INSERT in the game menu does nothing.

I've checked some things to see why wouldn't it work:
1. Checked my DirectX version (DirectX 12)
2. Checked my firewall settings (Mirror's Edge.exe and the launcher.exe both have permissions)
3. Checked whether my INSERT key even worked at all.

I can't figure out what is causing the issue. I tried compiling the project instead of downloading the launcher.exe, but I can't compile the Client project file (Client.dll is missing error), although I can compile the Launcher project file. I tested it and the result was the same. I would greatly appreciate if someone could help me or comment whether they're having the same issue.

**Comment by ThatFlint** [comment]
My friend has the same issue and got an error code 0xe1, do you know what the cause could be?
