### ISSUE TITLE
failed to open a handle to mirror's edge

### ISSUE THREAD

**Issue by GCMEDIC** [btbd/mmultiplayer#22]
so me and my friend just bought this game, for me it works but my friend has this error "failed to open a handle to mirror's edge"

**Comment by btbd** [comment]
@GCMEDIC Does he have an antivirus that's possibly blocking the launcher from opening a handle? Is the launcher being ran at a higher or equal privilege level to Mirror's Edge?

**Comment by GCMEDIC** [comment]
we tried to turn off the antivirus and it is being ran at the same privelege as mirror's edge, still the same error

**Comment by btbd** [comment]
@GCMEDIC Well, there really isn't much I can do if the launcher doesn't have permission to open a handle to the game. Does it still happen if you start Mirror's Edge, go to main menu, then run the launcher?

**Comment by GCMEDIC** [comment]
welp, thanks, we still didn't suceed tho, but yeah, thanks for trying to help

**Comment by Nolram12345** [comment]
I have the same issue.

**Comment by Nolram12345** [comment]
I have tried adding Antivirus exception, running as Admin, running from a batchfile but nothing works.

**Comment by btbd** [comment]
@Nolram12345 @GCMEDIC The issue was caused by Mirrors Edge being ran under a different user than the launcher, thus without debug privileges (regardless of admin) the launcher cannot open a handle. The new launcher should fix it: https://github.com/btbd/mmultiplayer/releases/tag/2.0
