### ISSUE TITLE
Bug : NPCs are broken

### ISSUE THREAD

**Issue by Nolram12345** [btbd/mmultiplayer#25]
When playing in Multiplayer and triggering NPCs, those NPCs do neither do their actions (like chase the player or shoot them), and seem to focus players at random but never take action. This blocks gameplay a lot.

**Comment by btbd** [comment]
@Nolram12345 Fixed. Next time you launch your client should be updated. See 91d2229c9034e8640dd6016cbb632c669ed53ed5.
