### ISSUE TITLE
Option to Disable Multiplayer

### ISSUE THREAD

**Issue by BoffinBrain** [btbd/mmultiplayer#28]
I know multiplayer is the core intention of this tool, but I'm mostly using it for the trainer and camera features, and I'm currently having to block the exe with my firewall to stop random people joining the session. It would be great to have an option to toggle multiplayer support on/off and have it persist in settings.

**Comment by btbd** [comment]
@BoffinBrain I could add this feature in the future, but this is not really a priority by any means as you can just join a room that nobody else is in.

**Comment by BoffinBrain** [comment]
I think the most confusing part is that it automatically connects without asking the user. I wouldn't be worried at all if joining or hosting a session was done on demand.
