### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by jramseygreen** [btbd/mmultiplayer#33]
Ryzen 7 2700x
16gb ram
windows 10 enterprise 64bit

Steam version of mirror's edge

Upon trying to open the launcher I am presented with the message (see screenshot) from windows; "This app can't run on your PC     To find a version for your PC, check with the software publisher"
![eedb950f664dc877067976bf66135173](https://user-images.githubusercontent.com/44009946/105929741-29c6cd00-6040-11eb-8933-929e650a0929.png)

**Comment by btbd** [comment]
According to your screenshot, the launcher executable you downloaded is an empty file. Ensure your download succeeded.
