### ISSUE TITLE
Chat working but can't see each other

### ISSUE THREAD

**Issue by biosmanager** [btbd/mmultiplayer#4]
I built from the latest commit with the new server IP but my friend and I can't see each other.
Chat works fine (but not always).
Enabling debug output didn't give us any clues other than client count always stayed 0, even when we were both in the same room.
Does this work with the Steam version of the game?

**Comment by btbd** [comment]
This is an issue with the server due to this: https://github.com/btbd/mmultiplayer/issues/3

The commit changing the IP and port was done prematurely before throrough testing with the new host. Until there is a new release closing these issues, the server is still not behaving as previously.

**Comment by biosmanager** [comment]
I see.
Another problem is that my friend can't open ports on his side so I guess it wouldn't work either.
My idea was to change the server script to get local IPs, host it locally, run the whole thing with a VPN and pass the server IP as an argument to MMultiplayer.exe.
Would that work?

**Comment by btbd** [comment]
Nice! The issue with the public server should be fixed now with the newest release.
