### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by Jimboiskewl** [btbd/mmultiplayer#5]
Please Can You Do A youtube Video Or Something On How To Setup The Mod Please?
I Cant Figure Out How To Do It. I Read The Instructions But I Dont Get Them Because Im Bad At Technical Stuff On PC's So Please Can You Make A Youtube Video On How To Set It up Please? Thanks

**Comment by biosmanager** [comment]
Currently the masterserver is not working properly, As soon as everything is back to normal using this mod is easy.
1. Download the mod, extract it somewhere, launch MMultiplayer.exe (preferably with administrator priviliges, right-click -> Run as administrator), choose a name, model and room, click Apply
2. Start Mirrors Edge (preferably with administrator priviliges, if you have it on Steam, start Steam as admin first)
3. Play a level, all players in the same room and on the same level will be visible to you

**Comment by Jimboiskewl** [comment]
Thanks But When You Select A room Do You Write The Name Of The Room So For Prolouge You Would type prolouge in the room select?

**Comment by Jimboiskewl** [comment]
Oh And When I Dowload There Is No MMultiplayer.exe File.
Any Ideas Why?

**Comment by biosmanager** [comment]
The room is just a number. People on the same room can see each other. So if you and your friend are the only people in room 123, only you can see each other.
You have to download the latest release, not the source code.

**Comment by Jimboiskewl** [comment]
Where Is The Latest release?

**Comment by btbd** [comment]
You can find the latest release here: https://github.com/btbd/mmultiplayer/releases

**Comment by Jimboiskewl** [comment]
Thanks btbd! :D

**Comment by Jimboiskewl** [comment]
Is Everything Working With The mod?
