### ISSUE TITLE
Cant See Each Other And Chat wont Work

### ISSUE THREAD

**Issue by Jimboiskewl** [btbd/mmultiplayer#6]
I Cant See My Friend And Chat Wont Work For Him But it Works For me

Yes Firewall is Of And Were On The Same Internet And Mirrors edge and the mod is running as admin on both machines and advice?

**Comment by Toyro98** [comment]
"_LAN is currently not supported._" I think your friend has to use different IP and not use the same as yours.

**Comment by Jimboiskewl** [comment]
Does LAN Mean Your On The Same Internet?

**Comment by Jimboiskewl** [comment]
We Do Have Different IP Adresses

**Comment by Toyro98** [comment]
Have you tried restarting Medge and MEMP? I once had to restart my pc to get MEMP working.

**Comment by Jimboiskewl** [comment]
Whats MEMP?

**Comment by Jimboiskewl** [comment]
Is It Mirrors edge Multiplayer?

**Comment by Toyro98** [comment]
Yes.

**Comment by Jimboiskewl** [comment]
I Know But My Friends Chat Wont Work.He Types Something But It Dosent Come Up As He Wrote Something

**Comment by Jimboiskewl** [comment]
Any Ideas Why?

**Comment by Toyro98** [comment]
Did he read the README.md?

**Comment by Jimboiskewl** [comment]
No. But Ive Disabled Firewall on Both PC's And Run BOth Things As Admin On Both Pc's

**Comment by Jimboiskewl** [comment]
Could You Like Make A Youtube Tutorial On Doing It Or Something Please?

**Comment by Jimboiskewl** [comment]
Please?

**Comment by Toyro98** [comment]
Sure.

**Comment by Jimboiskewl** [comment]
Thanks :D Whats your Youtube?

**Comment by Toyro98** [comment]
Same name as my Github.

**Comment by Jimboiskewl** [comment]
Thanks Alot Dude It Means Alot That SOmeone Uses There Time For Me Thanks Alot :D

**Comment by Jimboiskewl** [comment]
Can You Tell Me When Its Uploaded?

**Comment by Toyro98** [comment]
Yeah.

**Comment by Jimboiskewl** [comment]
Thanks Dude It Means Alot Thanks :D

**Comment by Jimboiskewl** [comment]
Uploaded?

**Comment by Toyro98** [comment]
Have you tried starting the game and multiplayer normally? Without "Start as Admin"?

**Comment by Jimboiskewl** [comment]
no

**Comment by Jimboiskewl** [comment]
have you made the vid?

**Comment by Jimboiskewl** [comment]
just a question

**Comment by Toyro98** [comment]
Try starting the game and multiplayer normally without "Start as Admin".

**Comment by Jimboiskewl** [comment]
k

**Comment by Jimboiskewl** [comment]
Thx For Advice

**Comment by Jimboiskewl** [comment]
Can We Play Together?

**Comment by Toyro98** [comment]
Only a quick test then. Room 5645 in Prologue.

**Comment by Jimboiskewl** [comment]
Wait gtg be back in like 10 to 20 mins bai

**Comment by Jimboiskewl** [comment]
back

**Comment by Jimboiskewl** [comment]
Hello?

**Comment by Jimboiskewl** [comment]
You There?

**Comment by Toyro98** [comment]
Yeah. I'm in room 5654 in chapter 2.

**Comment by Jimboiskewl** [comment]
You Mean Flight 
For Chapter 2?

**Comment by Jimboiskewl** [comment]
my name is kickglitcher

**Comment by Jimboiskewl** [comment]
oh k

**Comment by Jimboiskewl** [comment]
is it still gonna work cus ur in sweden and im in a diff country?

**Comment by Toyro98** [comment]
Yes. Just join the room 5645.

**Comment by Jimboiskewl** [comment]
k

**Comment by Jimboiskewl** [comment]
did it say i joined?

**Comment by Jimboiskewl** [comment]
what checkpoint in jacknife?

**Comment by Toyro98** [comment]
C

**Comment by Jimboiskewl** [comment]
k

**Comment by Toyro98** [comment]
https://discord.gg/Y5J3Zh

**Comment by Jimboiskewl** [comment]
can u send kg tool again plz?

**Comment by Jimboiskewl** [comment]
my pc crashed

**Comment by Jimboiskewl** [comment]
thats why i left

**Comment by Toyro98** [comment]
https://discord.gg/Y5J3Zh

**Comment by Jimboiskewl** [comment]
um dude

**Comment by Jimboiskewl** [comment]
is it allowed that u just gave me a invite cus i went on a me thread and it said to dm steven glowpunk to get a invite for server so.. is it allowed that u just gave me discord?

**Comment by Toyro98** [comment]
Yeah.

**Comment by Jimboiskewl** [comment]
k thx and where exactly is the kg tool in discord? plz?
