### ISSUE TITLE
Cant See Each other

### ISSUE THREAD

**Issue by Jimboiskewl** [btbd/mmultiplayer#8]
i cant see my friend and his chat dosent work asin if he writes something it wont cont come up in chat.

is it because were on the same internet?

i did this with someone on a different internet and it worked fine

**Comment by Toyro98** [comment]
_Try these 4 below._

_1. Is he running Mirror's Edge at a lower privilege than the mmultiplayer.exe?_

_2. Has he tried starting Mirror's Edge and mmultiplayer.exe without as  "Start as Admin"?_

_3. Has he tried removing all mmultiplayer.exe from the firewall and started mmultiplayer.exe with only selecting the "public networks"?_

_4. If he starts multiplayer before you, does your chat work?_

**Comment by Jimboiskewl** [comment]
Thx il try them

**Comment by Jimboiskewl** [comment]
didnt work

**Comment by Jimboiskewl** [comment]
Any Help?

**Comment by Jimboiskewl** [comment]
Chat Works But I cant see him and he cant see me

**Comment by btbd** [comment]
Closing this issue because it was resolved in the Discord server.
